apiVersion: aether.dev/v1alpha
kind: IdentityInstanceUpgrade
metadata:
  name: cloud-iam-ferriskey-upgrade-2600
  namespace: test-aether
spec:
  identityInstanceRef:
    name: cloud-iam-ferriskey
  targetVersion: "0.3.0"
  strategy: rolling
  approved: true
