apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
  namespace: test-aether
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: app
      owner: app
---
apiVersion: aether.dev/v1alpha
kind: IdentityInstance
metadata:
  name: keycloak-example
  namespace: test-aether
spec:
  organisationId: org-123
  provider: keycloak
  version: "25.0.0"
  hostname: localhost
  database:
    host: cluster-example-rw.test-aether.svc.cluster.local
    port: 5432
    name: app
    credentialsSecret: cluster-example-app
